Parameters:
    RegistryName:
        Type: String
        Description: Name of registry
    Environment:
        Type: String
        Description: Registry Environment
Resources:
    Registry:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: !Ref RegistryName
            Tags: 
                - 
                    Key: "owner"
                    Value: "Product"
                -
                    Key: "Project"
                    Value: "API"
                -
                    Key: "Env"
                    Value: !Ref Environment